In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.isna().sum() # qaysi qatorda qancha bo'sh qiymatlar borligini ko'rsatadi

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
(df.isna().sum() / len(df)) * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [ ]:
df['Age'] = df['Age'].fillna(df["Age"].median()) # Age qatoridagi bo'sh qiymatlarga median qiymatlarni qo'shadi

In [ ]:
df['Cabin'] = df['Cabin'].fillna("Noma'lum")

In [ ]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0]) # mode — statistikada "eng ko'p takrorlanuvchi qiymat" degani

In [ ]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
df.drop(columns=["Ticket"]) # "Ticket" ustunini o'chirib tashlash

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,Noma'lum,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,Noma'lum,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,Noma'lum,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,Noma'lum,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,23.4500,Noma'lum,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,Noma'lum,Q

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Noma'lum,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q

In [ ]:
df.drop(index=[0,1]) # 0 va 1 indexdagi qatorlarni o'chirib tashlash

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Noma'lum,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Noma'lum,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q

In [ ]:
df["OilaSoni"] = df["SibSp"] + df["Parch"] # Bu — SibSp (aka-uka/er-xotin soni) va Parch (ota-ona/farzand soni) ustunlarini qo'shib, yangi "oila a'zolari soni" ustunini yaratadi.

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,OilaSoni
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Noma'lum,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q,0

In [ ]:
yangi_qator = pd.DataFrame([{"PassengerId": 892, "Survived": 1, "Pclass": 1, "Name": "Test Odam", "Sex": "male", "Age": 30, "SibSp": 0, "Parch": 0, "Fare": 50, "Cabin": "Noma'lum", "Embarked": "S", "OilaSoni":0}])
df = pd.concat([df, yangi_qator], ignore_index=True) # ignore_index=True — yangi qatorga to'g'ri, ketma-ket indeks berilishini ta'minlaydi.

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,OilaSoni
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q,0
891,892,1,1,Test Odam,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0

In [ ]:
# task_1 Ticket va PassengerId ustunlarini olib tashlang (bu ustunlar tahlil uchun unchalik foydali emas — nega deb o'ylaysiz, bir jumla bilan izohlang).
df.drop(columns=["PassengerId"])

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,OilaSoni
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q,0
891,1,1,Test Odam,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0

In [ ]:
# task_2 Yangi ustun qo'shing — Yolgizmi (agar OilaSoni == 0 bo'lsa True, aks holda False):
df["Yolgizmi"] = df['OilaSoni'] == 0

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,OilaSoni,Yolgizmi
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,True
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True
891,892,1,1,Test Odam,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True

In [ ]:
df.shape

(892, 14)

In [ ]:
# task_3 Fare ustunida qiymati 0 bo'lgan barcha qatorlarni toping va ularni olib tashlang (bu — chipta narxi noldan katta bo'lishi kerak degan mantiqiy tekshiruv):
df[df['Fare'] != 0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,OilaSoni,Yolgizmi
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,True
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True
891,892,1,1,Test Odam,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True

In [ ]:
df.shape

(892, 14)

In [ ]:
# task_4 Pclass, Sex, Fare ustunlarini mos ravishda Toifa, Jins, Narx deb qayta nomlang (bitta rename() chaqiruvida, uchtasini birga).
df = df.rename(columns={"Pclass":"Toifa", "Sex":"Jins", "Fare":"Narx"})

In [ ]:
df

,PassengerId,Survived,Toifa,Name,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,True
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True
891,892,1,1,Test Odam,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True

In [ ]:
# task_5 Name ustunini indeks qilib belgilang (set_index("Name")), so'ng df.head() bilan natijani ko'ring — indeks endi ism ekanligini tasdiqlang.
df = df.set_index("Name")

In [ ]:
df.head()

,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
Name,,,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True

In [ ]:
# task_6 Yuqoridagi o'zgarishni bekor qiling — reset_index() bilan yana oddiy raqamli indeksga qaytaring.
df = df.reset_index()

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True

In [ ]:
# task_7 .iloc[0] bilan birinchi qatorni, .loc[0] bilan ham birinchi qatorni oling — natijalar bir xil chiqadimi? (Nega yoki nega yo'q — o'ylab ko'ring, indeks hozir qanday ekanini eslang.)
df.loc[0]

Name           Braund, Mr. Owen Harris
PassengerId                          1
Survived                             0
Toifa                                3
Jins                              male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Narx                              7.25
Cabin                         Noma'lum
Embarked                             S
OilaSoni                             1
Yolgizmi                         False
Name: 0, dtype: object

In [ ]:
df.iloc[0]

Name           Braund, Mr. Owen Harris
PassengerId                          1
Survived                             0
Toifa                                3
Jins                              male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Narx                              7.25
Cabin                         Noma'lum
Embarked                             S
OilaSoni                             1
Yolgizmi                         False
Name: 0, dtype: object

In [ ]:
# task_8 .iloc[:, 0:3] — barcha qatorlar, lekin faqat birinchi 3 ta ustun. Natijani ko'ring.
df.iloc[:, 0:3]

                                                  Name  PassengerId  Survived
0                              Braund, Mr. Owen Harris            1         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...            2         1
2                               Heikkinen, Miss. Laina            3         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)            4         1
4                             Allen, Mr. William Henry            5         0
..                                                 ...          ...       ...
887                       Graham, Miss. Margaret Edith          888         1
888           Johnston, Miss. Catherine Helen "Carrie"          889         0
889                              Behr, Mr. Karl Howell          890         1
890                                Dooley, Mr. Patrick          891         0
891                                          Test Odam          892         1

[892 rows x 3 columns]

In [ ]:
# task_9 .loc[df["Age"] > 60] — 60 yoshdan katta barcha yo'lovchilarni toping (bu — .loc ning shartli tanlash uchun ham ishlatilishini ko'rsatadi).
df.loc[df["Age"]>60]

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
33,"Wheadon, Mr. Edward H",34,0,2,male,66.0,0,0,C.A. 24579,10.5000,Noma'lum,S,0,True
54,"Ostby, Mr. Engelhart Cornelius",55,0,1,male,65.0,0,1,113509,61.9792,B30,C,1,False
96,"Goldschmidt, Mr. George B",97,0,1,male,71.0,0,0,PC 17754,34.6542,A5,C,0,True
116,"Connors, Mr. Patrick",117,0,3,male,70.5,0,0,370369,7.7500,Noma'lum,Q,0,True
170,"Van der hoef, Mr. Wyckoff",171,0,1,male,61.0,0,0,111240,33.5000,B19,S,0,True
252,"Stead, Mr. William Thomas",253,0,1,male,62.0,0,0,113514,26.5500,C87,S,0,True
275,"Andrews, Miss. Kornelia Theodosia",276,1,1,female,63.0,1,0,13502,77.9583,D7,S,1,False
280,"Duane, Mr. Frank",281,0,3,male,65.0,0,0,336439,7.7500,Noma'lum,Q,0,True
326,"Nysveen, Mr. Johan Hansen",327,0,3,male,61.0,0,0,345364,6.2375,Noma'lum,S,0,True
438,"Fortune, Mr. Mark",439,0,1,male,64.0,1,4,19950,263.0000,C23 C25 C27,S,5,False
456,"Millet, Mr. Francis Davis",457,0,1,male,65.0,0,0,13509,26.5500,E38,S,0,True
483,"Turkula, Mrs. (Hedwig)",484,1,3,female,63.0,0,0,4134,9.5875,Noma'lum,S,0,True
493,"Artagaveytia, Mr. Ramon",494,0,1,male,71.0,0,0,PC 17609,49.5042,Noma'lum,C,0,True
545,"Nicholson, Mr. Arthur Ernest",546,0,1,male,64.0,0,0,693,26.0000,Noma'lum,S,0,True
555,"Wright, Mr. George",556,0,1,male,62.0,0,0,113807,26.5500,Noma'lum,S,0,True
570,"Harris, Mr. George",571,1,2,male,62.0,0,0,S.W./PP 752,10.5000,Noma'lum,S,0,True
625,"Sutton, Mr. Frederick",626,0,1,male,61.0,0,0,36963,32.3208,D50,S,0,True
630,"Barkworth, Mr. Algernon Henry Wilson",631,1,1,male,80.0,0,0,27042,30.0000,A23,S,0,True
672,"Mitchell, Mr. Henry Michael",673,0,2,male,70.0,0,0,C.A. 24580,10.5000,Noma'lum,S,0,True
745,"Crosby, Capt. Edward Gifford",746,0,1,male,70.0,1,1,WE/P 5735,71.0000,B22,S,2,False
829,"Stone, Mrs. George Nelson (Martha Evelyn)",830,1,1,female,62.0,0,0,113572,80.0000,B28,S,0,True
851,"Svensson, Mr. Johan",852,0,3,male,74.0,0,0,347060,7.7750,Noma'lum,S,0,True

In [ ]:
# task_10 (farqni sinash):
df.loc[0:3]

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False

In [ ]:
df.iloc[0:3]

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True

In [ ]:
# task_11 .loc[0, "Age"] = 99 bilan 0-qatordagi yoshni 99 ga o'zgartiring, so'ng tasdiqlang.
df.loc[0, "Age"] = 99

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True

In [ ]:
df["Age"].isna().sum()

np.int64(0)

In [ ]:
# task_12 df.duplicated().sum() — Titanic'da nechta to'liq takroriy qator borligini toping (ehtimol 0 chiqadi, chunki har bir yo'lovchi noyob).
df.duplicated().sum()

np.int64(0)

In [ ]:
# task_13 Faqat Name ustuni bo'yicha takrorlanishni tekshiring (ba'zan turli odamlar bir xil ismga ega bo'lishi mumkin):
df.duplicated(subset=["Name"]).sum()

np.int64(0)

In [ ]:
# task_14 Agar 2-mashqda takroriy ism topilsa, ularni ko'rsating:
df[df.duplicated(subset=["Name"], keep=False)] # keep=False — bu barcha takroriy nusxalarni (birinchisini ham) ko'rsatadi, standart holatda faqat ikkinchi va keyingi nusxalar "takror" deb belgilanadi.

Empty DataFrame
Columns: [Name, PassengerId, Survived, Toifa, Jins, Age, SibSp, Parch, Ticket, Narx, Cabin, Embarked, OilaSoni, Yolgizmi]
Index: []

In [ ]:
# task_15 sun'iy takror yaratib sinash
df_test = pd.concat([df, df.iloc[[0]]], ignore_index=True)

In [ ]:
df_test

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True
892,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False

In [ ]:
df_test.duplicated().sum()

np.int64(1)

In [ ]:
df_test = df_test.drop_duplicates()

In [ ]:
df_test.duplicated().sum()

np.int64(0)

In [ ]:
# task_16 .map() yordamida, Sex ustunidagi "male"/"female" qiymatlarini "Erkak"/"Ayol" ga o'zgartirib, yangi JinsUZ ustuniga saqlang.
df["JinsUz"] = df["Jins"].map(lambda x : "Erkak" if x=="male" else "Ayol")

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi,JinsUz
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False,Erkak
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False,Ayol
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True,Ayol
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False,Ayol
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True,Erkak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True,Ayol
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False,Ayol
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True,Erkak
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True,Erkak
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True,Erkak

In [ ]:
# task_17 .apply() yordamida, Age asosida yangi YoshToifasi ustunini yarating: 18 dan kichik bo'lsa "Bola", 18-60 orasida "Kattalar", 60 dan katta bo'lsa "Keksa".
df["yoshToifasi"] = df["Age"].apply(lambda x: "Bola" if x<18 else ("Kattalar" if x<60 else "Keksalar"))

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi,JinsUz,yoshToifasi
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False,Erkak,Keksalar
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False,Ayol,Kattalar
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True,Ayol,Kattalar
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False,Ayol,Kattalar
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True,Erkak,Kattalar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True,Ayol,Kattalar
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False,Ayol,Kattalar
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True,Erkak,Kattalar
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True,Erkak,Kattalar
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True,Erkak,Kattalar

In [ ]:
# task_18 Alohida funksiya yozing, Fare asosida chipta narxini toifalarga ajratadi:
def narx_toifasi(narx):
  if narx<10:
    return "Arzon"
  elif narx<50:
    return "O'rta"
  else:
    return "Qimmat"
df["NarxToifasi"] = df["Narx"].apply(narx_toifasi)

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi,JinsUz,yoshToifasi,NarxToifasi
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False,Erkak,Keksalar,Arzon
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False,Ayol,Kattalar,Qimmat
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True,Ayol,Kattalar,Arzon
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False,Ayol,Kattalar,Qimmat
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True,Erkak,Kattalar,Arzon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True,Ayol,Kattalar,O'rta
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False,Ayol,Kattalar,O'rta
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True,Erkak,Kattalar,O'rta
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True,Erkak,Kattalar,Arzon
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True,Erkak,Kattalar,Qimmat

In [ ]:
# task_19 df["NarxToifasi"].value_counts() bilan har bir toifada nechta yo'lovchi borligini ko'ring.
df['NarxToifasi'].value_counts()

NarxToifasi
O'rta     394
Arzon     336
Qimmat    162
Name: count, dtype: int64

In [ ]:
pd.crosstab(df["Toifa"], df["NarxToifasi"]) # Bu — ikkita kategoriyaviy ustun orasidagi bog'liqlikni ko'rsatadigan jadval (masalan, "1-toifadagi yo'lovchilarning qanchasi haqiqatan ham 'Qimmat' toifasiga tushadi").

NarxToifasi  Arzon  O'rta  Qimmat
Toifa
1                6     70     141
2                6    171       7
3              324    153      14

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi,JinsUz,yoshToifasi,NarxToifasi
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False,Erkak,Keksalar,Arzon
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False,Ayol,Kattalar,Qimmat
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True,Ayol,Kattalar,Arzon
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False,Ayol,Kattalar,Qimmat
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True,Erkak,Kattalar,Arzon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True,Ayol,Kattalar,O'rta
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False,Ayol,Kattalar,O'rta
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True,Erkak,Kattalar,O'rta
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True,Erkak,Kattalar,Arzon
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True,Erkak,Kattalar,Qimmat

In [ ]:
# task_20 Name ustunidan familiyani ajratib oling (vergulgacha bo'lgan qism):
df["Familiya"] = df["Name"].str.split(",").str[0]

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi,JinsUz,yoshToifasi,NarxToifasi,Familiya
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False,Erkak,Keksalar,Arzon,Braund
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False,Ayol,Kattalar,Qimmat,Cumings
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True,Ayol,Kattalar,Arzon,Heikkinen
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False,Ayol,Kattalar,Qimmat,Futrelle
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True,Erkak,Kattalar,Arzon,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True,Ayol,Kattalar,O'rta,Graham
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False,Ayol,Kattalar,O'rta,Johnston
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True,Erkak,Kattalar,O'rta,Behr
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True,Erkak,Kattalar,Arzon,Dooley
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True,Erkak,Kattalar,Qimmat,Test Odam

In [ ]:
# task_21 Name ustunida "Mrs." so'zi bor-yo'qligini tekshirib, yangi TurmushQurgan (Boolean) ustunini yarating:
df["TurmushQurgan"] = df["Name"].str.contains("Mrs.")

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi,JinsUz,yoshToifasi,NarxToifasi,Familiya,TurmushQurgan
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False,Erkak,Keksalar,Arzon,Braund,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False,Ayol,Kattalar,Qimmat,Cumings,True
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True,Ayol,Kattalar,Arzon,Heikkinen,False
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False,Ayol,Kattalar,Qimmat,Futrelle,True
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True,Erkak,Kattalar,Arzon,Allen,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True,Ayol,Kattalar,O'rta,Graham,False
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False,Ayol,Kattalar,O'rta,Johnston,False
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True,Erkak,Kattalar,O'rta,Behr,False
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True,Erkak,Kattalar,Arzon,Dooley,False
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True,Erkak,Kattalar,Qimmat,Test Odam,False

In [ ]:
# task_22 Cabin ustunida (bo'sh bo'lmaganlarida) faqat birinchi harfni (kabina palubasi kodi) ajratib, yangi Paluba ustuniga saqlang:
df["Paluba"] = df["Cabin"].str[0]

In [ ]:
df

,Name,PassengerId,Survived,Toifa,Jins,Age,SibSp,Parch,Ticket,Narx,Cabin,Embarked,OilaSoni,Yolgizmi,JinsUz,yoshToifasi,NarxToifasi,Familiya,TurmushQurgan,Paluba
0,"Braund, Mr. Owen Harris",1,0,3,male,99.0,1,0,A/5 21171,7.2500,Noma'lum,S,1,False,Erkak,Keksalar,Arzon,Braund,False,N
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,False,Ayol,Kattalar,Qimmat,Cumings,True,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Noma'lum,S,0,True,Ayol,Kattalar,Arzon,Heikkinen,False,N
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1,False,Ayol,Kattalar,Qimmat,Futrelle,True,C
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,Noma'lum,S,0,True,Erkak,Kattalar,Arzon,Allen,False,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0,True,Ayol,Kattalar,O'rta,Graham,False,B
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,Noma'lum,S,3,False,Ayol,Kattalar,O'rta,Johnston,False,N
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C,0,True,Erkak,Kattalar,O'rta,Behr,False,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Noma'lum,Q,0,True,Erkak,Kattalar,Arzon,Dooley,False,N
891,Test Odam,892,1,1,male,30.0,0,0,NaN,50.0000,Noma'lum,S,0,True,Erkak,Kattalar,Qimmat,Test Odam,False,N

In [ ]:
# task_23 Paluba ustunidagi har bir qiymatdan nechtadan borligini ko'ring ("N" — "Noma'lum" so'zining birinchi harfi bo'lishi kerak, buni alohida kuzating):
df["Paluba"].value_counts()

Paluba
N    688
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [ ]:
mijozlar = pd.DataFrame({
    "mijoz_id": [1, 2, 3],
    "ism": ["Ali", "Vali", "Sami"]
})

buyurtmalar = pd.DataFrame({
    "buyurtma_id": [101, 102, 103],
    "mijoz_id": [1, 2, 1],
    "summa": [50000, 30000, 20000]
})

In [ ]:
# task_24 Yuqoridagi mijozlar va buyurtmalar DataFrame'larini yarating, pd.merge() bilan birlashtiring, natijani ko'ring.
natija = pd.merge(mijozlar, buyurtmalar, on="mijoz_id")

In [ ]:
natija

   mijoz_id   ism  buyurtma_id  summa
0         1   Ali          101  50000
1         1   Ali          103  20000
2         2  Vali          102  30000

In [ ]:
# task_25 mijozlar ga yana bir mijoz qo'shing — {"mijoz_id": 4, "ism": "Nodira"} — lekin unga hech qanday buyurtma bermang. Endi how="left" bilan birlashtiring — Nodira natijada ko'rinadimi? summa ustunida uning qatorida nima chiqadi?
mijozlar = pd.DataFrame({
    "mijoz_id": [1, 2, 3, 4],
    "ism": ["Ali", "Vali", "Sami", "Nodira"]
})

pd.merge(mijozlar, buyurtmalar, on="mijoz_id", how="left")

   mijoz_id     ism  buyurtma_id    summa
0         1     Ali        101.0  50000.0
1         1     Ali        103.0  20000.0
2         2    Vali        102.0  30000.0
3         3    Sami          NaN      NaN
4         4  Nodira          NaN      NaN

In [ ]:
# task_26 Xuddi shu ikkita jadvalni how="inner" bilan birlashtiring — Nodira bu safar ko'rinadimi? Farqni tushuntiring.
pd.merge(mijozlar, buyurtmalar, on="mijoz_id", how="inner")

   mijoz_id   ism  buyurtma_id  summa
0         1   Ali          101  50000
1         1   Ali          103  20000
2         2  Vali          102  30000

In [ ]:
savdo = pd.DataFrame({
    "oy": ["Yanvar", "Yanvar", "Fevral", "Fevral"],
    "mahsulot": ["Non", "Sut", "Non", "Sut"],
    "miqdor": [100, 80, 120, 90]
})

In [ ]:
# task_27 Yuqoridagi savdo DataFrame'ni yarating, pivot_table bilan oy va mahsulot bo'yicha jadval hosil qiling.
pivot = savdo.pivot_table(values="miqdor", index="oy", columns="mahsulot", aggfunc="sum")

In [ ]:
pivot

mahsulot  Non  Sut
oy
Fevral    120   90
Yanvar    100   80

In [ ]:
# task_28 Titanic'ga qaytib, pivot_table yordamida Toifa (Pclass) va Jins (Sex) bo'yicha, o'rtacha Ageni ko'rsating:
df.pivot_table(values="Age", index="Toifa", columns="Jins", aggfunc="mean")

Jins      female       male
Toifa
1      33.978723  38.922114
2      28.703947  30.512315
3      23.572917  27.133775

In [ ]:
# task_29 Sun'iy sana ustuni yarating va undan yil/oy/kun ajratib oling:
sanalar = pd.DataFrame({"sana": ["2023-01-15", "2023-06-20", "2024-03-10"]})
sanalar

         sana
0  2023-01-15
1  2023-06-20
2  2024-03-10

In [ ]:
sanalar.dtypes

sana    object
dtype: object

In [ ]:
sanalar["sana"] = pd.to_datetime(sanalar["sana"])
sanalar

        sana
0 2023-01-15
1 2023-06-20
2 2024-03-10

In [ ]:
sanalar.dtypes

sana    datetime64[ns]
dtype: object

In [ ]:
sanalar["yil"] = sanalar["sana"].dt.year
sanalar

        sana   yil
0 2023-01-15  2023
1 2023-06-20  2023
2 2024-03-10  2024

In [ ]:
sanalar["oy"] = sanalar["sana"].dt.month
sanalar

        sana   yil  oy
0 2023-01-15  2023   1
1 2023-06-20  2023   6
2 2024-03-10  2024   3

In [ ]:
sanalar["kun"] = sanalar["sana"].dt.day
sanalar

        sana   yil  oy  kun
0 2023-01-15  2023   1   15
1 2023-06-20  2023   6   20
2 2024-03-10  2024   3   10

In [ ]:
sanalar["hafta_kuni"] = sanalar["sana"].dt.day_name()
sanalar

        sana   yil  oy  kun hafta_kuni
0 2023-01-15  2023   1   15     Sunday
1 2023-06-20  2023   6   20    Tuesday
2 2024-03-10  2024   3   10     Sunday

In [ ]:
sanalar["bugun"] = pd.to_datetime("2026-07-22")
sanalar["necha_kun_otgan"] = (sanalar["bugun"] - sanalar["sana"]).dt.days
sanalar

        sana   yil  oy  kun hafta_kuni      bugun  necha_kun_otgan
0 2023-01-15  2023   1   15     Sunday 2026-07-22             1284
1 2023-06-20  2023   6   20    Tuesday 2026-07-22             1128
2 2024-03-10  2024   3   10     Sunday 2026-07-22              864