In [21]:
# ==============================================
# NETFLIX KONTENT TAHLILI
# Maqsad: Netflixdagi film va seriallar bo'yicha
# umumiy tendensiyalarni aniqlash
# ==============================================
import pandas as pd

# Ma'lumotni yuklaymiz
from google.colab import files
uploaded = files.upload()

Saving netflix_titles.csv to netflix_titles (1).csv

In [22]:
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [23]:
# --------Ma'lumot sifatini tekshirish--------
# bo'sh qiymatlar qancha va qaysi ustunlarda ekanini ko'ramiz
print(df.isna().sum())
print("\nBo'sh qiymatlar foizda")
print(df.isna().sum() / len(df) *100)

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

Bo'sh qiymatlar foizda
show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

In [24]:
# director ustunida bo'sh qiymatlar asosan TV Show turidagi kontentga tegishli
# (chunki serialda bir nechta epizod rejissyori bo'lishi mumkin, bitta emas)
# Shuning uchun bu tabiiy holat, "Noma'lum" bilan belgilaymiz
df["director"] = df['director'].fillna("Noma'lum")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Noma'lum,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [25]:
df[df['cast'].isna()]["type"].value_counts()

type
Movie      475
TV Show    350
Name: count, dtype: int64

In [26]:
# cast bo'shligi biror bitta turga aniq bog'liq emas (Movie va TV Show deyarli teng taqsimlangan),
# shuning uchun bu tasodifiy bo'shliq deb hisoblaymiz va "Noma'lum" bilan belgilaymiz
df["cast"] = df['cast'].fillna("Noma'lum")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [27]:
# country ustunini eng ko'p takrorlangan mamlakat nomi bilan to'ldiramiz
df["country"] = df["country"].fillna(df["country"].mode()[0])

In [28]:
# date_added bu taxmin qilish qiyin bo'lgan ma'lumaot, xatolik ehtimoli ko'p bo'lganligi uchun bo'sh qatorlarni o'chirib tashlaymiz
df = df.dropna(subset="date_added")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [29]:
# rating ustunidagi bo'sh qiymatlarni eng ko'p takrorlangan qiymat bilan to'ldiramiz
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])

In [30]:
df[df["duration"].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [31]:
# duration ustunida mavjud bo'lmagan qiymatlar rating ustunidagi mos qatorlarga o'tib qolgan. Qiymatlarni to'g'ri joyga ko'chiramiz
mask = df["duration"].isna()
df.loc[mask, "duration"] = df.loc[mask, "rating"]

In [32]:
# rating ustunidan ko'chirilgan ma'lumotlarni (74 min, 84 min, 66 min) eng ko'p takrorlangan rating bilan almashtiramiz
df.loc[mask, "rating"] = df["rating"].mode()[0]
df.loc[[5541, 5794, 5813]]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,TV-MA,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,TV-MA,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,TV-MA,66 min,Movies,The comic puts his trademark hilarious/thought...

In [33]:
# show_id — shunchaki identifikator, tahliliy ma'no bermaydi, olib tashlaymiz
df = df.drop(columns="show_id")
df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [34]:
# Har bir kontent nechta janrga tegishli ekanini hisoblaymiz —
# bu keyinchalik "ko'p janrli kontent ko'proq mashhurmi" kabi savollarga yordam beradi
df["JanrSoni"] = df["listed_in"].str.split(",").str.len()
df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,JanrSoni
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1
1,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3
3,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2
4,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3

In [35]:
# Kontentni chiqarilgan yiliga qarab "Eski" va "Yangi" toifalarga bo'lamiz —
# bu Netflix'ning so'nggi yillardagi tendensiyasini ko'rish uchun foydali
df["Eski_yoki_yangi"] = df["release_year"].apply(lambda x: "Yangi" if x>=2015 else "Eski")
df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Yangi
1,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,Yangi
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Yangi
3,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Yangi
4,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,Yangi

In [36]:
df.shape

(8797, 13)

In [37]:
# Yillar bo'yicha, Netflix qaysi turdagi kontentga (Movie/TV Show) ko'proq e'tibor bergan? (Maslahat: date_added dan yilni ajratib, groupby yoki
# pivot_table bilan type bo'yicha taqsimotni ko'ring)
# pivot_table yordamida har bir yilda qaysi kontentga ko'proq e'tibor berilganini ko'ramiz

In [38]:
# date_added ichidan yillarni ajratib olamiz
# date_added ichida str formatni sanaga o'zgartiramiz
df["date_added"] = df["date_added"].str.strip()
df["date_added"] = pd.to_datetime(df["date_added"])

# Sanadan faqat yilni ajratib olamiz
df["Qo'shilgan_yil"] = df["date_added"].dt.year

In [39]:
pivot = df.pivot_table(values="title", index="Qo'shilgan_yil", columns="type", aggfunc="count")
pivot["Nisbat"] = pivot["Movie"] / pivot["TV Show"]
pivot

type             Movie  TV Show    Nisbat
Qo'shilgan_yil
2008               1.0      1.0  1.000000
2009               2.0      NaN       NaN
2010               1.0      NaN       NaN
2011              13.0      NaN       NaN
2012               3.0      NaN       NaN
2013               6.0      5.0  1.200000
2014              19.0      5.0  3.800000
2015              56.0     26.0  2.153846
2016             253.0    176.0  1.437500
2017             839.0    349.0  2.404011
2018            1237.0    412.0  3.002427
2019            1424.0    592.0  2.405405
2020            1284.0    595.0  2.157983
2021             993.0    505.0  1.966337

In [40]:
# -------- Xulosa --------
# Netflix har doim Movie'ga TV Show'dan ko'proq e'tibor bergan (nisbat doimiy ravishda 2:1 dan 2.4:1 orasida), lekin 2016-2019 yillar oralig'ida ikkalasi
# ham keskin o'sgan — bu Netflix'ning eng faol kontent yaratish davri bo'lgan. 2020-2021 yillarda esa pasayish ko'rinadi (1424→1284→993 Movie uchun),
# bu ehtimol COVID-19 pandemiyasi ta'sirida ishlab chiqarish sekinlashgani bilan bog'liq bo'lishi mumkin — bu qiziqarli, tekshirish mumkin bo'lgan gipoteza.

In [41]:
# Qaysi 5 ta davlat eng ko'p kontent ishlab chiqargan? (Maslahat: value_counts() yodingizdami?)
df["country"].value_counts().head()

country
United States     3642
India              972
United Kingdom     418
Japan              244
South Korea        199
Name: count, dtype: int64

In [42]:
# Eng ko'p uchraydigan 5 ta janr qaysilar? (Diqqat: listed_in da bir nechta janr bitta katakchada, vergul bilan — buni avval qanday ajratganingizni eslang,
# keyin har bir janrni alohida sanash kerak bo'ladi — bu biroz qiyinroq, agar qiynalsangiz ayting)
df["listed_in"] = df["listed_in"].str.split(",")

In [47]:
df.explode("listed_in")["listed_in"].value_counts().head(5)

listed_in
 International Movies    2624
Dramas                   1600
Comedies                 1210
Action & Adventure        859
Documentaries             829
Name: count, dtype: int64

In [ ]:
# -------- Xulosa ----------
# "International Movies" — bu boshqa barcha janrlardan sezilarli darajada ko'p (2624 — keyingi eng yaqin Dramasdan 1000+ ko'p). Bu shuni ko'rsatadiki,
#  Netflix o'zining kontent strategiyasida xalqaro (mahalliy bo'lmagan) filmlarga katta e'tibor bergan — bu ehtimol Netflix'ning global bozorlarga
# (Hindiston, Janubiy Koreya, Lotin Amerikasi va h.k.) faol kirish strategiyasi bilan bog'liq.

In [48]:
# rating (masalan, TV-MA, PG-13) bilan Eski_yoki_yangi orasida qanday bog'liqlik bor — masalan, yangi kontentlarda qattiqroq reytinglar ko'proqmi?
# (Maslahat: pivot_table yoki crosstab)
pd.crosstab(df['Eski_yoki_yangi'], df['rating'])

rating,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
Eski_yoki_yangi,,,,,,,,,,,,,,
Eski,33,2,39,178,315,413,699,46,444,263,48,100,3,2
Yangi,8,1,40,109,175,386,1458,174,2768,598,258,233,3,1

In [ ]:
# ---------- Xulosa -----------
# Netflix'ning yangi kontenti (2015 yildan keyingi), eski kontentiga qaraganda, sezilarli darajada ko'proq kattalar uchun mo'ljallangan (TV-MA, TV-14)
# reytinglarga ega. Bu — Netflix'ning so'nggi yillarda kattalar auditoriyasiga ko'proq yo'naltirilgan kontent strategiyasini tanlaganini ko'rsatishi
# mumkin — ehtimol raqobat (HBO, boshqa striming xizmatlari) sababli, yoki o'z auditoriyasining o'sib, kattalar tomon siljigani sababli.

In [ ]:
# --------- Yakuniy xulosa --------
# Ushbu tahlil Netflix'ning kontent strategiyasidagi bir necha aniq tendensiyani ochib berdi. Birinchidan, platforma har doim filmlarga (Movie)
# seriallardan (TV Show) ko'proq e'tibor bergan, ammo 2016–2019 yillar Netflix uchun eng faol kontent yaratish davri bo'lgan, 2020 yildan keyin esa o'sish
# sur'ati sekinlashgan — bu, ehtimol, global pandemiya ta'sirida ishlab chiqarish jarayonlarining to'xtab qolishi bilan bog'liq bo'lishi mumkin.
# Ikkinchidan, "International Movies" boshqa barcha janrlardan sezilarli darajada ko'p (2624 ta), bu Netflix'ning AQShdan tashqari — xususan Hindiston va
# Janubiy Koreya kabi — bozorlarga faol kirish strategiyasini aks ettiradi. Uchinchidan, vaqt o'tishi bilan Netflix kontenti tobora "kattalar uchun"
# reytinglar (TV-MA, TV-14) tomon siljigan, bu esa platformaning auditoriyasi yoki raqobat muhiti o'zgarganidan darak beradi. Umuman olganda, ushbu
# ma'lumotlar Netflix'ning so'nggi o'n yil ichida global, xilma-xil va kattalarga yo'naltirilgan kontent kompaniyasiga aylanish yo'lini aniq ko'rsatib
# beradi.