In [14]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving netflix_titles.csv to netflix_titles (1).csv

In [15]:
df = pd.read_csv("netflix_titles.csv")
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [17]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [18]:
df.isna().sum() / len(df) * 100

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

In [19]:
df[df["director"].isna()]["type"].value_counts()

type
TV Show    2446
Movie       188
Name: count, dtype: int64

In [20]:
df["director"] = df["director"].fillna("Noma'lum") # director — MNAR (Missing Not At Random) (TV Show bilan bog'liq), "Noma'lum" bilan to'ldiramiz

In [21]:
df["cast"] = df["cast"].fillna("Noma'lum") #  cast — kam foiz, matn ustuni, "Noma'lum" mantiqiy

In [22]:
df["country"] = df["country"].fillna(df["country"].mode()[0]) # country — kam foiz, eng ko'p uchraydigan davlat bilan to'ldiramiz

In [23]:
df["rating"] = df["rating"].fillna(df["rating"].mode()[0]) # rating — juda kam bo'sh, mode bilan to'ldirish mantiqiy

In [24]:
df = df.dropna(subset=("date_added")) # date_added — sana, va foiz kam, shuning uchun bu qatorlarni olib tashlaymiz

In [25]:
df[df["duration"].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [26]:
mask = df["duration"].isna() # bu 3 ta muammoli qatorni belgilaydi (True/False ustuni)
df.loc[mask, "duration"] = df.loc[mask, "rating"] # o'sha 3 qatorda, ratingdagi qiymatni ("74 min") durationga ko'chiramiz
df.loc[mask, "rating"] =  df["rating"].mode()[0] # endi rating bo'shab qoldi, uni eng ko'p uchraydigan reyting bilan to'ldiramiz

In [27]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [28]:
# task_1 show_id ustunini olib tashlang (bu — shunchaki identifikator, tahlil uchun foydasiz — nega ekanini o'zingizga izohlang).
df = df.drop(columns=["show_id"])
df.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [37]:
# task_2 listed_in ustuni (janrlar, vergul bilan ajratilgan, masalan "Comedies, Dramas") asosida, yangi JanrSoni ustunini yarating — bu har bir film/serial nechta janrga tegishli ekanini ko'rsatsin (maslahat: .str.split(",") va uzunligini olish kerak bo'ladi — buni qanday birlashtirish mumkinligini o'ylab ko'ring).
df["JanrSoni"] = df["listed_in"].str.split(",").str.len()
df.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Yangi
1,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,Yangi
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Yangi
3,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Yangi
4,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,Yangi

In [38]:
# task_3 release_year asosida yangi Eski_yoki_yangi ustunini yarating — agar release_year >= 2015 bo'lsa "Yangi", aks holda "Eski" (shartli mantiq — 3-haftadagi bilimingizni eslang).
df["Eski_yoki_yangi"] = df['release_year'].map(lambda x: "Yangi" if x >= 2015 else "Eski")

In [33]:
df['Eski_yoki_yangi'].value_counts()

Eski_yoki_yangi
Yangi    6212
Eski     2585
Name: count, dtype: int64

In [35]:
# task_4 Yangi qator qo'shing — o'zingiz o'ylab topgan, hayoliy bitta film/serial ma'lumoti bilan (barcha ustunlarni to'ldirib).
yangi_qator = pd.DataFrame([{"type" : "Movie", "title" : "Qaroqchilar", "director" : "Ahad Qayum", "cast" : "Noma'lum", "country":"Uzbekistan", "date_added":"July 23, 2026", "release_year":2026, "rating":"Noma'lum", "duration":"70 min", "listed_in":"Fantastic", "description":"Noma'lum"}])
df = pd.concat([df, yangi_qator], ignore_index=True)

In [39]:
df

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Yangi
1,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,Yangi
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Yangi
3,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Yangi
4,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,Yangi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8793,TV Show,Zombie Dumb,Noma'lum,Noma'lum,United States,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",3,Yangi
8794,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2,Eski
8795,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2,Eski
8796,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,3,Yangi
8797,Movie,Qaroqchilar,Ahad Qayum,Noma'lum,Uzbekistan,"July 23, 2026",2026,Noma'lum,70 min,Fantastic,Noma'lum,1,Yangi

In [40]:
df.shape

(8798, 13)

In [41]:
# task_5 type, title, country ustunlarini mos ravishda Turi, Sarlavha, Davlat deb qayta nomlang (bitta rename() chaqiruvida).
df = df.rename(columns={"type":"Turi", "title":"Sarlavha", "country":"Davlat"})

In [42]:
df.head(5)

,Turi,Sarlavha,director,cast,Davlat,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Yangi
1,TV Show,Blood & Water,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,Yangi
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Yangi
3,TV Show,Jailbirds New Orleans,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Yangi
4,TV Show,Kota Factory,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,Yangi

In [43]:
# task_6 title (yoki yangi nomlangan Sarlavha) ustunini indeks qilib belgilang, natijani ko'ring.
df = df.set_index("Sarlavha")
df.head(5)

,Turi,director,cast,Davlat,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
Sarlavha,,,,,,,,,,,,
Dick Johnson Is Dead,Movie,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Yangi
Blood & Water,TV Show,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,Yangi
Ganglands,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Yangi
Jailbirds New Orleans,TV Show,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Yangi
Kota Factory,TV Show,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,Yangi

In [45]:
# task_7 Indeksni bekor qilib, yana oddiy raqamli indeksga qaytaring.
df = df.reset_index()
df.head(5)

,index,Sarlavha,Turi,director,cast,Davlat,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
0,0,Dick Johnson Is Dead,Movie,Kirsten Johnson,Noma'lum,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Yangi
1,1,Blood & Water,TV Show,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,Yangi
2,2,Ganglands,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Yangi
3,3,Jailbirds New Orleans,TV Show,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Yangi
4,4,Kota Factory,TV Show,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,Yangi

In [46]:
 # task_8 .iloc[100:105] bilan 100-104 qatorlarni oling (5 ta qator).
df.iloc[100:105]

,index,Sarlavha,Turi,director,cast,Davlat,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
100,100,Tobot Galaxy Detectives,TV Show,Noma'lum,"Austin Abell, Travis Turner, Cole Howard, Anna...",United States,"September 7, 2021",2019,TV-Y7,2 Seasons,Kids' TV,An intergalactic device transforms toy cars in...,1,Yangi
101,101,Untold: Breaking Point,Movie,"Chapman Way, Maclain Way",Noma'lum,United States,"September 7, 2021",2021,TV-MA,80 min,"Documentaries, Sports Movies",Under pressure to continue a winning tradition...,2,Yangi
102,102,Countdown: Inspiration4 Mission to Space,TV Show,Jason Hehir,Noma'lum,United States,"September 6, 2021",2021,TV-14,1 Season,"Docuseries, Science & Nature TV","From training to launch to landing, this all-a...",2,Yangi
103,103,Shadow Parties,Movie,Yemi Amodu,"Jide Kosoko, Omotola Jalade-Ekeinde, Yemi Blaq...",United States,"September 6, 2021",2020,TV-MA,117 min,"Dramas, International Movies, Thrillers",A family faces destruction in a long-running c...,3,Yangi
104,104,Tayo the Little Bus,TV Show,Noma'lum,"Robyn Slade, Kami Desilets",South Korea,"September 6, 2021",2016,TV-Y,2 Seasons,"Kids' TV, Korean TV Shows",As they learn their routes around the busy cit...,2,Yangi

In [50]:
# task_9 .loc yordamida, faqat Turi == "TV Show" va release_year > 2020 bo'lgan yozuvlarni toping (ikkita shartni birlashtiring).
df.loc[(df["Turi"]=="TV Show") & (df['release_year']>2020)]

,index,Sarlavha,Turi,director,cast,Davlat,date_added,release_year,rating,duration,listed_in,description,JanrSoni,Eski_yoki_yangi
1,1,Blood & Water,TV Show,Noma'lum,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,Yangi
2,2,Ganglands,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Yangi
3,3,Jailbirds New Orleans,TV Show,Noma'lum,Noma'lum,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Yangi
4,4,Kota Factory,TV Show,Noma'lum,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,Yangi
5,5,Midnight Mass,TV Show,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",United States,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,3,Yangi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,1460,Monarca,TV Show,Noma'lum,"Irene Azuela, Juan Manuel Bernal, Osvaldo Bena...",Mexico,"January 1, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...","After 20 years, Ana María returns to Mexico an...",3,Yangi
1551,1551,Hilda,TV Show,Noma'lum,"Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...","United Kingdom, Canada, United States","December 14, 2020",2021,TV-Y7,2 Seasons,Kids' TV,"Fearless, free-spirited Hilda finds new friend...",1,Yangi
1696,1696,Polly Pocket,TV Show,Noma'lum,"Emily Tennant, Shannon Chan-Kent, Kazumi Evans...","Canada, United States, Ireland","November 15, 2020",2021,TV-Y,2 Seasons,Kids' TV,After uncovering a magical locket that allows ...,1,Yangi
2920,2920,Love Is Blind,TV Show,Noma'lum,"Nick Lachey, Vanessa Lachey",United States,"February 13, 2020",2021,TV-MA,1 Season,"Reality TV, Romantic TV Shows",Nick and Vanessa Lachey host this social exper...,2,Yangi
8427,8427,The Netflix Afterparty,TV Show,Noma'lum,"David Spade, London Hughes, Fortune Feimster",United States,"January 2, 2021",2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London...",2,Yangi